# kerno/skills/builtins/export.py
"""
Built-in export skills for DataFrames and analysis artifacts.
"""

_EXPORT_SKILLS_CODE = r'''
import json as _json
from pathlib import Path as _Path

import pandas as pd
from IPython.display import display as _display, Markdown as _MD


def export_to_excel(dataframes: dict, path: str = "export.xlsx") -> str:
    """
    Export multiple DataFrames to one multi-sheet Excel workbook.
    """
    output = _Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        for sheet_name, df in dataframes.items():
            if not isinstance(df, pd.DataFrame):
                df = pd.DataFrame(df)
            df.to_excel(writer, sheet_name=str(sheet_name)[:31], index=False)
    print(f"✓ Exported {len(dataframes)} sheet(s) to {output.resolve()}")
    return str(output.resolve())


def generate_markdown_report(title: str, sections: dict, path: str = "report.md") -> str:
    """
    Generate a Markdown report from section-title/content pairs.

    DataFrames are rendered via ``to_markdown`` when tabulate is available.
    """
    lines = [f"# {title}", "", "*Generated by Kerno*", "", "---", ""]
    for heading, content in sections.items():
        lines.append(f"## {heading}")
        lines.append("")
        if isinstance(content, pd.DataFrame):
            try:
                lines.append(content.to_markdown(index=False))
            except Exception:
                lines.append(content.to_string(index=False))
        else:
            lines.append(str(content))
        lines.append("")
    output = _Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    _display(_MD(f"Report saved to `{output.resolve()}`"))
    return str(output.resolve())


def save_artifact(obj, name: str, format: str = "json") -> str:
    """
    Save a DataFrame, dict, list, or string under ``_artifacts``.
    """
    path = _Path("_artifacts") / f"{name}.{format}"
    path.parent.mkdir(parents=True, exist_ok=True)

    if isinstance(obj, pd.DataFrame):
        if format == "csv":
            obj.to_csv(path, index=False)
        elif format == "parquet":
            obj.to_parquet(path)
        else:
            obj.to_json(path, orient="records", indent=2, date_format="iso")
    elif isinstance(obj, (dict, list)):
        with open(path, "w", encoding="utf-8") as f:
            _json.dump(obj, f, indent=2, default=str)
    else:
        path.write_text(str(obj), encoding="utf-8")
    print(f"✓ Saved artifact: {path.resolve()} ({path.stat().st_size / 1024:.1f} KB)")
    return str(path.resolve())
'''


def get_code() -> str:
    return _EXPORT_SKILLS_CODE
